spring:
  #Configuración del data source
  datasource:
    url: jdbc:mysql://localhost:3306/spring_lab?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true # ¡CAMBIO AQUÍ!
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  #Configuración de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #Configuración de Jackson
  jackson:
    serialization:
      write-date-keys-as-timestamps: false

  #Configurar DevTools
  devtools:
    restart:
      enabled: true

#Configurar el servidor embebido (Tomcat)
server:
  port: 8080